spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/green_challenge
        username: root
        password: 1234
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
server:
    port: 8080
    error:
        include-stacktrace: never